apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "kubernetes-node-example"
  namespace: "default"
  labels:
    app: "kubernetes-node-example"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "kubernetes-node-example"
  template:
    metadata:
      labels:
        app: "kubernetes-node-example"
    spec:
      containers:
      - name: "mytestedimage-1"
        image: "gcr.io/nodejsapppoc/mytestnodejs/mytestedimage:v1"
        ports:
        - containerPort: 8887
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "kubernetes-node-example-hpa-sk1u"
  namespace: "default"
  labels:
    app: "kubernetes-node-example"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "kubernetes-node-example"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "kubernetes-node-example-service"
  namespace: "default"
  labels:
    app: "kubernetes-node-example"
spec:
  ports:
  - protocol: "TCP"
    port: 8887
    targetPort: 30001
  selector:
    app: "kubernetes-node-example"
  type: "LoadBalancer"
  loadBalancerIP: ""